spring:
  influxdb:
    url: http://localhost:8086
    username: " "
    password: " "
    database: telegraf
    retention-policy: autogen
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/turvo?useSSL=false
    username: root
    password: turvo