spring:
  influxdb:
    url: http://192.168.1.87:8086
    username: " "
    password: " "
    database: telegraf
    retention-policy: autogen
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/turvo?useSSL=false
    username: root
    password: turvo
server:
  port: 8081